### ISSUE TITLE
semaphores's performance differs a lot in fair and unfair mode

### ISSUE THREAD

**Issue by huotinghh** [bmc/javautil#22]
I use a semaphore in a complex system with 300 permits while the background workflow has 1000 concurrent requests. It takes about 7ms for processing after permit acquired.
For unfair semaphore, the delay for acquiring the permit is less than 1ms while delay for fair semaphore is more than 30ms.
I understand unfair semaphore may have a slightly better performance. But why it differs so much?

**Comment by bmc** [comment]
Honestly, without digging, I have no idea why this is happening. I rarely even use this library any more, as my preferred language on the JVM is Scala these days. I almost never do any Java programming. Also, if you're using the [`Semaphore`](https://github.com/bmc/javautil/blob/master/src/main/java/org/clapper/util/misc/Semaphore.java) class in this package, please note that I deprecated it some time ago:

---

NOTE: This interface, and its subclasses, are deprecated. With J2SE 5.0 (a.k.a., Java 1.5), the JDK provides its own semaphore class, `java.util.concurrent.Semaphore`.

---

And I will not claim to be an expert in `java.util.concurrent.Semaphore`, as it has been some time since I have needed its functionality.

Closing this issue, as (a) no one should be using my `Semaphore` class, and (b) problems with `java.util.concurrent.Semaphore` are out of the scope of this library.
